blank_issues_enabled: false
contact_links:
  - name: 🙋 Ask questions via Twitter (preferred)
    url: https://twitter.com/xKabbe
    about: Ask questions about the project or how you can contribute to the project yourself
