name: Test React Application
run-name: ${{ github.actor }} is testing 🧪 the React Application 💻

# Controls when the action will run.
on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # ID of the job
  react-jest-test:
    # Name of the job as it will be displayed in GitHub
    name: React Jest Test 🧪
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies 🪜
        run: npm install
      - name: Run Jest Tests 🪜
        run: npm test && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
      - name: Report Test Coverage to Coveralls 🪜
        run: COVERALLS_REPO_TOKEN=$coveralls_repo_token npm run coveralls
